### ISSUE TITLE
Issue with run demo site/admin

### ISSUE THREAD

**Issue by hvbnet** [BroadleafCommerce/CommunityStarter#11]
Hi

I have issue with run demo site. after config demo using [this link](https://www.broadleafcommerce.com/docs/core/current/getting-started/ide-setup/intellij-setup) 

I got this error 

> ***************************
> APPLICATION FAILED TO START
> ***************************
> 
> Description:
> 
> Constructor in org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration required a single bean, but 3 were found:
> 	- exporter: defined in class path resource [bl-common-applicationContext-mbeans.xml]
> 	- blAutoDDLStatusExporter: defined in class path resource [bl-common-applicationContext-mbeans.xml]
> 	- hibernateExporter: defined in class path resource [bl-common-applicationContext-mbeans.xml]
> 

how to solve issue this issue?

Please note that I using latest version (5.2)

**Comment by phillipuniverse** [comment]
I assume that you are running the project from the newest version of IntelliJ, 2017.2. The workaround is to disable "Enable JMX Agent" in the run configuration for the boot project.

I opened an issue for this at BroadleafCommerce/Issues/issues/1, this should be resolved in the next version of Broadleaf.
