### ISSUE TITLE
How to override wrapper

### ISSUE THREAD

**Issue by michalgce** [BroadleafCommerce/CommunityStarter#24]
Hi, is it possible to overwrapper wrapper for ex. ProductWrapper to take care and show additional parameters.

**Comment by cja769** [comment]
Hi, you should be able to add the following in your SiteConfiguration
```
@Bean("com.broadleafcommerce.rest.api.wrapper.ProductWrapper")
public ProductWrapper customerProductWrapperOverride() {
    return new MyProductWrapper();
}
```

**Comment by michalgce** [comment]
Thanks @cja769 easy and nice i also tried this approach and either works.
```
@ImportResource("classpath:applicationContext-wrapper.xml")
```

applicationContext-wrapper.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
                           http://www.springframework.org/schema/beans/spring-beans.xsd">

    <bean id="com.broadleafcommerce.rest.api.wrapper.ProductWrapper" class="com.community.api.wrappers.XSProductWrapper" scope="prototype" />
</beans>
```

which allows me to override lists of wrapper's.
Unfortunately CatalogEndpoint::findProductById return ProductImpl instead my override entity. 
For site module my override is returned correctly.

Response from SITE module:
![image](https://user-images.githubusercontent.com/1582983/32806673-ad9c1ede-c98d-11e7-9429-f7a02e475c20.png)

Response from REST module:
![image](https://user-images.githubusercontent.com/1582983/32806738-eacc49b4-c98d-11e7-8543-32d1f0b395ad.png)

**Comment by cja769** [comment]
@michalgce Correct. Those are synonymous. Glad I could help!

**Comment by cja769** [comment]
@michalgce Sorry I missed that last part though I'm a little confused. The response from SITE and REST look the same and seem to return your override

**Comment by michalgce** [comment]
As you can see @cja769 (orange labels) Site module returns XSProduct (my own class), and REST module ProductImpl (Default one).

No idea what's is wrong because both off them calls same DAOs methods. 😞

**Comment by cja769** [comment]
The orange labels both say XSProduct from what I can see
https://cl.ly/2A2r2M3i3J0c

**Comment by michalgce** [comment]
![image](https://user-images.githubusercontent.com/1582983/32808836-bae8504c-c994-11e7-975d-15d8ca8dd452.png)

**Comment by cja769** [comment]
Ok I think I needed to reload the issue. My mistake.

So in the core project you added a line similar to 
```
<bean id="org.broadleafcommerce.core.catalog.domain.Product"
          class="{package}.XSProduct" scope="prototype" />
```
in applicationContext-entity.xml?
