### ISSUE TITLE
mvn package is failing

### ISSUE THREAD

**Issue by mjspka** [BroadleafCommerce/CommunityStarter#35]
c:\work\git\broadleaf\DemoSite>mvn package
[INFO] Scanning for projects...
Downloading from public snapshots: http://nexus.broadleafcommerce.org/nexus/content/groups/community-snapshots/org/broadleafcommerce/broadleaf-boot-starter-parent/5.2.5.1-GA/broadleaf-boot-starter-parent-5.2.5.1-GA.pom
[WARNING] Checksum validation failed, expected <!DOCTYPE but is 73460fe408d190711a28060fbcb870c9ef00d26d from public snapshots for http://nexus.broadleafcommerce.org/nexus/content/groups/community-snapshots/org/broadleafcommerce/broadleaf-boot-starter-parent/5.2.5.1-GA/broadleaf-boot-starter-parent-5.2.5.1-GA.pom
[WARNING] Could not validate integrity of download from http://nexus.broadleafcommerce.org/nexus/content/groups/community-snapshots/org/broadleafcommerce/broadleaf-boot-starter-parent/5.2.5.1-GA/broadleaf-boot-starter-parent-5.2.5.1-GA.pom: Checksum validation failed, expected <!DOCTYPE but is 73460fe408d190711a28060fbcb870c9ef00d26d
[WARNING] Checksum validation failed, expected <!DOCTYPE but is 73460fe408d190711a28060fbcb870c9ef00d26d from public snapshots for http://nexus.broadleafcommerce.org/nexus/content/groups/community-snapshots/org/broadleafcommerce/broadleaf-boot-starter-parent/5.2.5.1-GA/broadleaf-boot-starter-parent-5.2.5.1-GA.pom
Downloaded from public snapshots: http://nexus.broadleafcommerce.org/nexus/content/groups/community-snapshots/org/broadleafcommerce/broadleaf-boot-starter-parent/5.2.5.1-GA/broadleaf-boot-starter-parent-5.2.5.1-GA.pom (6.9 kB at 7.7 kB/s)
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM C:\Users\malla\.m2\repository\org\broadleafcommerce\broadleaf-boot-starter-parent\5.2.5.1-GA\broadleaf-boot-starter-parent-5.2.5.1-GA.pom: Expected root element 'project' but found 'html' (position: START_TAG seen ....01//EN" "http://www.w3.org/TR/html4/strict.dtd">\n<html lang="en">... @2:17)  @ C:\Users\malla\.m2\repository\org\broadleafcommerce\broadleaf-boot-starter-parent\5.2.5.1-GA\broadleaf-boot-starter-parent-5.2.5.1-GA.pom, line 2, column 17
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.mycompany-community:boot-community-demo:1.0.0-SNAPSHOT (c:\work\git\broadleaf\DemoSite\pom.xml) has 1 error
[ERROR]     Non-parseable POM C:\Users\malla\.m2\repository\org\broadleafcommerce\broadleaf-boot-starter-parent\5.2.5.1-GA\broadleaf-boot-starter-parent-5.2.5.1-GA.pom: Expected root element 'project' but found 'html' (position: START_TAG seen ....01//EN" "http://www.w3.org/TR/html4/strict.dtd">\n<html lang="en">... @2:17)  @ C:\Users\malla\.m2\repository\org\broadleafcommerce\broadleaf-boot-starter-parent\5.2.5.1-GA\broadleaf-boot-starter-parent-5.2.5.1-GA.pom, line 2, column 17 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException

**Comment by cja769** [comment]
@mjspka Here's some things that ring alarms
> [WARNING] Checksum validation failed, expected \n... @2:17) 

and 

>  Expected root element 'project' but found 'html'

What this indicates to me is that when downloading the JAR the request seems to have returned a 404 page or, if you are going through a firewall, a firewall redirected you to a different url and downloaded the html from that page. If it's the latter then there's nothing we can do however I would suggest going to the `C:\Users\malla.m2\repository\org` directory and doing a `rm -rf broadleafcommerce` (or the Windows equivalent. After deleting this repository try running `mvn clean install` from the root directory (basically if you're in `/DemoSite/site` then do `cd ..`).
