### ISSUE TITLE
admin: No 'Access-Control-Allow-Origin' header is present on the requested resource 

### ISSUE THREAD

**Issue by timosalex** [BroadleafCommerce/CommunityStarter#49]
Hello,

I am getting this error every time I am trying to _submit_ something via the admin (let's say new product or sku):

` ERROR 3115 --- [o-12004-exec-25] b.o.w.c.e.AdminBasicOperationsController : [JS] - (https://mydomain.com/admin/js/admin/blc-admin.js:1329) - Uncaught TypeError: Cannot read property 'trim' of undefined
`

some background: this error started after I installed ssl on my server (so from http now it runs on https). 

In order to make the forced https redirection work on my server I disabled the direction from broadleaf. In site/adminsecurityconfig I erased :

```
   .requiresChannel()
             .antMatchers("/","/**")
              .antMatchers("/**")

             .requiresSecure()
          
```

is this known behaviour? any tips?

**Comment by timosalex** [comment]
also when I open the console window of my browser i get this:

```
Mixed Content: The page at 'https://mydomain.com/admin/product/10052#tab5' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://mydomain.com/admin/product/10052/productOptions/add'. This request has been blocked; the content must be served over HTTPS.
send @ jquery-2.1.1.min.js:4

```

**Comment by cja769** [comment]
I've seen that error before but if I recall it's a common symptom of many different problems. As far as the SSL thing, are you running the application behind a load balancer or something? 

edit: The second message is pretty much like it sounds. You need to sort out the HTTP/HTTPS issues

**Comment by timosalex** [comment]
tbh I don't know what a load balancer is but I didn't configure my tomcat server.xml for the redirection port. So I had to disable the spring redirection from broadleaf, assigned a ssl certificate and did a forced https redirection from my cpanel. 

I am having a secure page everywhere. When I login to the admin and go for instance to categories though I get a semi-secure page. I think this has to do with js as when you do a submition on admin it calls http and not https

**Comment by timosalex** [comment]
also when I enable chrome to run non secure scripts I get a 

`Access to XMLHttpRequest at 'http://mydomain.com/admin/product/10052/productOptions/add' from origin 'https://mydomain.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`

I am looking how to add this header on tomcat.

**Comment by timosalex** [comment]
So the error I am getting is this basically:

`Access to XMLHttpRequest at 'http://example.com/admin/product/10052/productOptions/add' from origin 'https://exampls.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`


Still haven't figure out a solution. I think I have to change SiteSecurityConfig and AdminSecurityConfig (not sure if i have to change both though). 

I am doing something like this on Site/AdminSecurityConfig:

```
@Configuration
@EnableWebSecurity
@EnableGlobalMethodSecurity(securedEnabled = true, prePostEnabled = true)
public class SiteSecurityConfig extends WebSecurityConfigurerAdapter {

@Override
protected void configure(HttpSecurity http) throws Exception {
    http
    .cors().and()
         //.....
         }


  @Bean
    CorsConfigurationSource corsConfigurationSource() {
        CorsConfiguration configuration = new CorsConfiguration();
        configuration.setAllowedOrigins(Arrays.asList("https://example.com"));
        configuration.setAllowedHeaders(Arrays.asList("Access-Control-Allow-Headers"));
        configuration.addExposedHeader("Access-Control-Allow-Headers");
        configuration.setAllowedMethods(Arrays.asList("POST"));
        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        source.registerCorsConfiguration("/**", configuration);
        return source;
    }
}

``` 
Still trying to work around it
I have opened a stackoverflow [thread ](https://stackoverflow.com/questions/55284078/no-access-control-allow-origin-header-is-present-on-the-requested-resource-sp)as well


My question is though: if the site and the admin run on a different domain for some reason, wouldn't this problem occur? A cors() configuration wouldn't be neccesary?

thanks!

**Comment by phillipuniverse** [comment]
@timosalex based on the other issue you opened at #48, sounds like you are deploying onto a very specific hosting provider. What hosting provider are you deploying to?

> tbh I don't know what a load balancer is but I didn't configure my tomcat server.xml for the redirection port.

A load balancer is a server that sits in front of your Tomcat server that receives requests from the external web, listening on port 80 and 443. Without a load balancer (like when you are running on your local computer), your web requests work like this:

```
USER BROWSER ------> TOMCAT SERVER
```

When you add in a load balancer, it causes the request to work like this:

```
USER BROWSER -------> LOAD BALANCER ------> TOMCAT SERVER
```

The other advantage is that it also allows for "load balancing" between many servers:

```
                                     |---> TOMCAT SERVER-1
USER BROWSER -----> LOAD BALANCER  --|
                                     |---> TOMCAT SERVER-2
```

The issue that you are running into I believe is that you _are_ running behind some sort of load balancer in your hosting provider somewhere. Here is where problems come in with https behind a load balancer: when the user browser connects to port 443 to load the page, it connects to the load balancer port 443. But behind the scenes, the load balancer connects to Tomcat, sometimes _not_ on port 443, and also not over https. Here's a diagram of the situation:

```
USER BROWSER ------> (port 443, https) LOAD BALANCER ------> (port 8080, http) TOMCAT SERVER
```

Now in Tomcat, Tomcat only sees the connection from the load balancer, which is on port 8080. This means that Spring Security thinks that it is serving the page over http (which it is, back to the connection at the load balancer), then it tries to redirect to https, then you get in the redirect loop. I'm not sure how you resolved this in #48, but likely that is causing this next issue.

The real solution is to either not run behind a load balancer like this:

```
USER BROWSER -------> (443, https) TOMCAT SERVER
```

Or, have the load balancer send over `X-Forwarded-Proto` and `X-Forwarded-for`. These are really straightforward with Spring Boot, see https://docs.spring.io/spring-boot/docs/2.0.6.RELEASE/reference/html/howto-security.html#howto-enable-https. Then it works like this:

```
USER BROWSER ---> (port 443, https) LOAD BALANCER ---> (port 8080, http, X-Forwarded-Proto=https) TOMCAT SERVER
```

This way, even though Tomcat is communicating directly with the load balancer of http, it trusts that X-Forwarded-Proto header and treats the request as https. This makes it to where Spring Security also treats the request as SSL and does not redirect.

If you are deploying to Tomcat directly, you will need to add the RemoteIpValve to `server.xml` to detect these headers: https://tomcat.apache.org/tomcat-8.5-doc/api/org/apache/catalina/valves/RemoteIpValve.html. Finally, you will need to ensure that the load balancer actually sends that header.

**Comment by timosalex** [comment]
@phillipuniverse totally grateful to you for spending time to write such an extensive solution.

I obsessively studied proxy, reverse proxy, load balancer etc the last couple of days and I am extremely glad that you confirm and add to my knowledge with your answer. So I am posting the solution here cause I
think that a lot of people will find it interesting the future.

So first of all:

> What hosting provider are you deploying to?



Mochahost (is the one that you thought or amazon?)

So I have a vps running centos and then I deployed root and admin on an account running tomcat there

Let's forget ssl atm. In order to make it run as http I had to erase requiresSecure() from Site/AdminSecurityConfig. This worked perfectly fine.

Then I tried to configure tomcat the way I do in my local machine following all the documentation and the guides  available and to re-enter requiresSercure() on spring security in broadleaf . So I added the connector in tomcat's  server.xml:

```
 <Connector SSLEnabled="true" protocol="org.apache.coyote.http11.HTTP11NioProtocol" 
 clientAuth="false" keystoreFile="conf/blc-example.keystore" keystorePass="broadleaf" 
 keyPass="broadleaf" maxThreads="150" port="8443" scheme="https" secure="true" sslProtocol="TLS"/>

``` 
 this still didn't work and it is still unclear to me why. However my tomcat is on 12004 and not 8080
 
     <Connector port="12004" protocol="HTTP/1.1" 
               connectionTimeout="20000" 
               redirectPort="8443" />

			    
so I  added a portMapper() from 12004 to 8443 on spring security. Still didn't work. As far as I understand we are here:

`client browser -> loadbalancer(http) ->tomcat(redirects to https) -> broadleaf 
`
It didn't work and still don't know why.

So I erased requiresSecure() and I installed a ssl certificate (on the load balancer, this is clear to me now) 
and forced https redirect

`browser -> loadbalancer (https) -> tomcat(http)->broadleaf (doesn't require secure)
`
This worked perfectly fine. Until I reached to the problem which I opened the thread initially, with cors. 

`Access to XMLHttpRequest at 'http: //example.com/admin/add' from origin 'https: //example.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`

**SOLUTION 1**

_(I am not proposing it at all as it is hacky and has security risks but as I spend so much time to figure it
out I think it's worth posting it for educational purposes)_

```
@Configuration
@EnableWebSecurity
@EnableGlobalMethodSecurity(securedEnabled = true, prePostEnabled = true)
public class SiteSecurityConfig extends WebSecurityConfigurerAdapter {

@Override
protected void configure(HttpSecurity http) throws Exception {
    http
    .cors().and()
         //.....
         }


  @Bean
    CorsConfigurationSource corsConfigurationSource() {
        CorsConfiguration configuration = new CorsConfiguration();
        configuration.setAllowedOrigins(Arrays.asList("https://example.com","http://example.com"));
        configuration.setAllowedHeaders(Arrays.asList("Access-Control-Allow-Headers"));
        configuration.addExposedHeader("Access-Control-Allow-Headers");
        configuration.setAllowedMethods(Arrays.asList("POST"));
        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        source.registerCorsConfiguration("/**", configuration);
        return source;
    }
}


```
**SOLUTION 2**

**(the real thing based on philip comments and this is the proper way)**

Using requiresSecure() on spring security (as it is broadleaf "out-of-the-box")
On .properties adding these two lines :

```
server.tomcat.remote-ip-header=x-forwarded-for
server.tomcat.protocol-header=x-forwarded-proto

```
(I was lucky enough that the load balancer (front-end proxy) was sending these by default)

And the most tricky part for me. On tomcat's server.xml erase the connector thing about 8443 
and add this two lines on default port 

```
    <Connector port="12004" protocol="HTTP/1.1" 
               connectionTimeout="20000" 
               secure="true"
               scheme="https" 
               redirectPort="8443" />

```
The `secure="true"` and `scheme="https"`  was what needed and now everything works fine	:)

**Comment by phillipuniverse** [comment]
Thanks for sharing your investigation and final solution!

> Let's forget ssl atm. In order to make it run as http I had to erase requiresSecure() from Site/AdminSecurityConfig. This worked perfectly fine.

True, if you want to do http only, this is what you would do. The reason we ship with https by default (and serve _everything_ over https) is because [Google gives you better a better SEO score when all your pages are https](https://webmasters.googleblog.com/2014/08/https-as-ranking-signal.html).

> this still didn't work and it is still unclear to me why. However my tomcat is on 12004 and not 8080

Yeah the connector thing is really the key here. The load balancer connects to your Tomcat instance on port 120004, so the SSL connector in this case does nothing. You had essentially the right idea with modifying the port mappings in spring security, as that port mapping is essentially telling the _user_ (via a 302 redirect) which port it should redirect to. We have some additional "light" reading on configuring and dealing with different Spring Security port mappings in different environments at https://github.com/BroadleafCommerce/BroadleafCommerce/issues/424.

Anyway, @timosalex thanks again for taking the time to report back and helping the community at large with investigating these difficult-to-debug issues!
