### ISSUE TITLE
Mixed Content: The page at 'https://localhost:8443/merchandise/heat_clinic_hand-drawn_mens' was loaded over HTTPS, but requested an insecure font 'https:'. This request has been blocked; the content must be served over HTTPS.

### ISSUE THREAD

**Issue by xbitlabs** [BroadleafCommerce/CommunityStarter#52]
![未命名-2](https://user-images.githubusercontent.com/9734921/60693893-9df5c900-9f0e-11e9-8e91-e79ff4bc98e0.jpg)
![未命名-1](https://user-images.githubusercontent.com/9734921/60693895-a0582300-9f0e-11e9-8f3e-ee6fe7c692dd.jpg)

**Comment by cja769** [comment]
Tested with 6.1 and modernizr is being retrieved over HTTPS like it should be. This issue seems to have been fixed at some point
