### ISSUE TITLE
103.135.230.174 redirected you too many times. ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by vkhatri87** [BroadleafCommerce/CommunityStarter#61]
Hi,
Looking for the help for below issue .
When i try to run broadleaf site as independent application on tomcat it works fine when actually when i deploy it on centos 7 VPS it gives error as ERR_TOO_MANY_REDIRECTDS
After  refering the link [https://github.com/BroadleafCommerce/DemoSite/issues/49](https://github.com/BroadleafCommerce/DemoSite/issues/49) i have changed the application.properties and added below mentioned properties but then also could not succeed!!

server.tomcat.remote-ip-header=x-forwarded-for
server.tomcat.protocol-header=x-forwarded-proto

below is the generated logs

server started 

Attempting to load ESAPI.properties via file I/O.
Attempting to load ESAPI.properties as resource file via file I/O.
Not found in 'org.owasp.esapi.resources' directory or file not readable: /usr/local/tomcat8/bin/ESAPI.properties
Not found in SystemResource Directory/resourceDirectory: .esapi/ESAPI.properties
Not found in 'user.home' (/root) directory: /root/esapi/ESAPI.properties
Loading ESAPI.properties via file I/O failed. Exception was: java.io.FileNotFoundException
Attempting to load ESAPI.properties via the classpath.
SUCCESSFULLY LOADED ESAPI.properties via the CLASSPATH from 'esapi/' using current thread context class loader!
Attempting to load validation.properties via file I/O.
Attempting to load validation.properties as resource file via file I/O.
Not found in 'org.owasp.esapi.resources' directory or file not readable: /usr/local/tomcat8/bin/validation.properties
Not found in SystemResource Directory/resourceDirectory: .esapi/validation.properties
Not found in 'user.home' (/root) directory: /root/esapi/validation.properties
Loading validation.properties via file I/O failed.
Attempting to load validation.properties via the classpath.
SUCCESSFULLY LOADED validation.properties via the CLASSPATH from 'esapi/' using current thread context class loader!
2020-06-07 10:17:44.214  INFO 21978 --- [nio-8443-exec-9] o.h.cache.internal.StandardQueryCache    : HHH000248: Starting query cache at region: query.Order
2020-06-07 10:17:44.323  INFO 21978 --- [nio-8443-exec-9] o.h.cache.internal.StandardQueryCache    : HHH000248: Starting query cache at region: query.Catalog
2020-06-07 10:17:44.368  INFO 21978 --- [nio-8443-exec-9] o.h.cache.internal.StandardQueryCache    : HHH000248: Starting query cache at region: query.Cms
2020-06-07 10:17:44.408  INFO 21978 --- [nio-8443-exec-9] o.b.c.s.util.GenericCookieUtilsImpl      : HTTP cookie set regardless of the value of isSecure.
2020-06-07 10:17:44.409  INFO 21978 --- [nio-8443-exec-9] .p.w.s.s.SessionFixationProtectionFilter : Session has been terminated. ActiveID did not match expected value.
2020-06-07 10:17:44.447  INFO 21978 --- [io-8443-exec-10] o.b.c.s.util.GenericCookieUtilsImpl      : HTTP cookie set regardless of the value of isSecure.
2020-06-07 10:17:44.480  INFO 21978 --- [io-8443-exec-10] o.b.c.s.util.GenericCookieUtilsImpl      : HTTP cookie set regardless of the value of isSecure.
2020-06-07 10:17:44.481  INFO 21978 --- [io-8443-exec-10] .p.w.s.s.SessionFixationProtectionFilter : Session has been terminated. ActiveID did not match expected value.
2020-06-07 10:17:44.521  INFO 21978 --- [nio-8443-exec-2] o.b.c.s.util.GenericCookieUtilsImpl      : HTTP cookie set regardless of the value of isSecure.
2020-06-07 10:17:44.553  INFO 21978 --- [nio-8443-exec-2] o.b.c.s.util.GenericCookieUtilsImpl      : HTTP cookie set regardless of the value of isSecure.
2020-06-07 10:17:44.554  INFO 21978 --- [nio-8443-exec-2] .p.w.s.s.SessionFixationProtectionFilter : Session has been terminated. ActiveID did not match expected value.
2020-06-07 10:17:44.601  INFO 21978 --- [nio-8443-exec-1] o.b.c.s.util.GenericCookieUtilsImpl      : HTTP cookie set regardless of the value of isSecure.
2020-06-07 10:17:44.617  INFO 21978 --- [nio-8443-exec-1] o.b.c.s.util.GenericCookieUtilsImpl      : HTTP cookie set regardless of the value of isSecure.
2020-06-07 10:17:44.618  INFO 21978 --- [nio-8443-exec-1] .p.w.s.s.SessionFixationProtectionFilter : Session has been terminated. ActiveID did not match expected value.
2020-06-07 10:17:44.648  INFO 21978 --- [nio-8443-exec-5] o.b.c.s.util.GenericCookieUtilsImpl      : HTTP cookie set regardless of the value of isSecure.
2020-06-07 10:17:44.666  INFO 21978 --- [nio-8443-exec-5] o.b.c.s.util.GenericCookieUtilsImpl      : HTTP cookie set regardless of the value of isSecure.
2020-06-07 10:17:44.667  INFO 21978 --- [nio-8443-exec-5] .p.w.s.s.SessionFixationProtectionFilter : Session has been terminated. ActiveID did not match expected value.
2020-06-07 10:17:44.696  INFO 21978 --- [nio-8443-exec-3] o.b.c.s.util.GenericCookieUtilsImpl      : HTTP cookie set regardless of the value of isSecure.

**Comment by phillipuniverse** [comment]
If you have a load balancer configured in front of your VPS, you might also need to trust the IP address that sets those headers. This is done with the server.tomcat.remoteip.internal-proxies property.

The value of this is a regex of the upstream IP address(es) of the load balancer. Importantly, this is the IP address that your application sees (usually an internal IP address) not the external IP address of the load balancer.

**Comment by phillipuniverse** [comment]
That said, based on your logs it appears that you are deploying a .war onto Tomcat itself and you are not running a fat .jar file with embedded Tomcat.

If that is the case, those properties will not work. Instead, you need to [configure the RemoteIPValve](http://tomcat.apache.org/tomcat-8.5-doc/api/org/apache/catalina/valves/RemoteIpValve.html) yourself.

Another way to diagnose whether or not this is truly the problem is to look at the Network tab in your browser when it sends requests. If you are getting 301s, what is the value of the ‘Location’ header in each response? What is the value of the full URL you are visiting each time that triggers the redirect (including http/https)?

**Comment by vkhatri87** [comment]
Hi @phillipuniverse thanks alot for taking a timeout and replying, i want to just update i am not using any loadbalancer so not sure RemoteIPValve needs to be configured in that case also ?

Also i have added the below mentioned entry in server.xml but could not succeed
<Valve className="org.apache.catalina.valves.RemoteIpValve" internalProxies="127\.0\.[0-1]\.1" remoteIpHeader="x-forwarded-for" requestAttributesEnabled="true" protocolHeader="x forwarded-proto" protocolHeaderHttpsValue="https"/> 
[RemoteIPValve.txt](https://github.com/BroadleafCommerce/DemoSite/files/4747650/RemoteIPValve.txt)

**Comment by vkhatri87** [comment]
below entry made in server.xml 
<Valve className="org.apache.catalina.valves.RemoteIpValve"
          internalProxies="127\.0\.[0-1]\.1"
          remoteIpHeader="x-forwarded-for"
          requestAttributesEnabled="true"
          protocolHeader="x-forwarded-proto"
          protocolHeaderHttpsValue="https"/>

**Comment by phillipuniverse** [comment]
If you are definitely not behind a load balancer and RemoteIPValve doesn’t apply, what is the full url (including http/https) of the request you are sending and the response header “Location” you get back? If you are in a browser, you can find this information by going to the Network tab in the developer tools.

**Comment by phillipuniverse** [comment]
Looking at the RemoteIPValve configuration, I don’t think that will work because it will only trust values from 127.0.0.1 (localhost). If you don’t have an upstream load balancer in front of Tomcat at all then you should not use RemoteIPValve.

**Comment by phillipuniverse** [comment]
@vkhatri87 I went to http://103.135.230.174 and noticed that is using HTTPD. This would fall under the same "load balancer" type of discussion. If you use anything sitting in front of Tomcat (like httpd or nginx or whatever) to proxy connections, you need the `RemoteIPValve`.

Could you post the configuration settings you are using for httpd to connect to Tomcat? This would be any `ProxyPass...` entries.

Also, could you post your tomcat `server.xml` that has your `<Connector>` that httpd uses to connect to it?

**Comment by vkhatri87** [comment]
Hi @phillipuniverse  thanks alot for replying..
yes i am not using any loadbalaancer here, i am hitting a url as https://103.135.230.174:8443/ in which the  response headers "Location" is coming as blank i.e ("/") with status code as 302
Please find the attached server.xml for the same
[server.txt](https://github.com/BroadleafCommerce/DemoSite/files/4766323/server.txt)

"

**Comment by phillipuniverse** [comment]
I have seen this problem before but haven't really been able to reliably reproduce it.

I think you are safe to remove this filter then:

https://github.com/BroadleafCommerce/DemoSite/blob/6065ad92e23474cfeff32be6c6d9fc974ecfc67d/site/src/main/java/com/community/configuration/SiteSecurityConfig.java#L151

I think this is the thing that is actually sending that redirect to `/`: https://github.com/BroadleafCommerce/BroadleafCommerce/blob/e6fd522d023188168e069dce5000d94f42729d7a/core/broadleaf-profile-web/src/main/java/org/broadleafcommerce/profile/web/site/security/SessionFixationProtectionFilter.java#L117

Try removing it out of the filter chain there and see if it works. We wrote that to begin with for a couple of reasons:

1. We wanted to be able to retain a session cookie between ssl and non-ssl -- this isn't really a valid use case anymore as all sites should be SSL-only and not switch between protocols in normal use
2. Spring Security didn't have OOB support for this -- now they do, they have their own session fixation attack support

@cja769  @danielcolgrove might be something to dig into further to remove this altogether from the filter chain.

**Comment by cja769** [comment]
@phillipuniverse I've created a ticket to remove Broadleaf's `SessionFixationProtectionFilter` and replace it with a logging filter that checks if any requests are insecure and recommend using Spring's `SessionFixationProtectionStrategy` if they're going to have requests over HTTP

**Comment by vkhatri87** [comment]
@phillipuniverse  thanks again for your inputs..
as instructed, i have simply removed that line from SiteSecurityConfig.java file
But now it fails in getting the locale with below mentioned error

org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "'locale-' + session.blLocale.localeCode" 

attaching the complete stacktrace..
[errorlogs.txt](https://github.com/BroadleafCommerce/DemoSite/files/4774774/errorlogs.txt)
Also wanted to update, after this change war file works perfectly as expected in local enviornment, but the issue is there in VPS
please suggest how to proceed with this..

**Comment by cja769** [comment]
This is typically an error that shows up if another error was thrown and it's redirecting to a 400/500/etc page and, looking at the stacktraces, they're both going through the `ErrorPageFilter` . Change
```
'locale-' + session.blLocale.localeCode
```
to
```
'locale-' + session.blLocale != null ? session.blLocale.localeCode : 'en_US'`
```
There's possibly other areas as well that aren't null safe. 

Alternatively if you have a custom `error.html` or `error/500.html` and it's using `fullPageLayout.html` you may want to simplify that page to get to the root issue.

**Comment by phillipuniverse** [comment]
One other thing to check: make sure you actually have data in the `BLC_LOCALE` tables. If you don't have an entry marked as the default locale, it could also throw an NPE as the [LocaleResolver](https://github.com/BroadleafCommerce/BroadleafCommerce/blob/e6fd522d023188168e069dce5000d94f42729d7a/common/src/main/java/org/broadleafcommerce/common/web/BroadleafLocaleResolverImpl.java#L98-L108) could return null.

Honestly, that whole expression at https://github.com/BroadleafCommerce/DemoSite/blob/c88229dbbed1fd189b175978ccf0e4d8ab8f825b/site/src/main/resources/webTemplates/layout/fullPageLayout.html#L18 should probably be rewritten to be:

```html
 <body th:class="${'locale-' + blLocaleCode} +' index-page'"> 
```

so that it will use the one set as a request attribute and not always pull from session.

**Comment by vkhatri87** [comment]
Hi @phillipuniverse , @cja769 ,
Thanks a ton guys for your inputs, just posting comments after few days since i am still struggling with it.
As per your inputs in fullPageLayout.html i have replaced the line 

 `<body th:class="${'locale-' + session.blLocale.localeCode} +' index-page'">`
with this line 
 `<body th:class="locale-en_US +' index-page'">`
after this i am trying to hit the url https://103.135.230.174:8443/login which shows me a login and register customer page successfully.
But please note that i am having a valid customer entry in blc_customer table with which i am trying to login but not able to succeed with it as it shows that email and password do not match(though i am entering a valid creds then also not able to login).
Also please be updated that i have created a war file of only site project and not added any other stuff for api and core project.
Also when i am trying to register a new customer though UI then also it is not allowing me to do so(please refer the error logs
[errorlogs_registercustomer.txt](https://github.com/BroadleafCommerce/DemoSite/files/4832761/errorlogs_registercustomer.txt)
)

**Comment by cja769** [comment]
@vkhatri87 It looks like it can't find the role it's looking for. Per the stacktrace it looks like the problem is starting from

```
    @Override
    public void createRegisteredCustomerRoles(Customer customer) {
        Role role = roleDao.readRoleByName("ROLE_USER");
        CustomerRole customerRole = new CustomerRoleImpl();
        customerRole.setRole(role);
        customerRole.setCustomer(customer);
        roleDao.addRoleToCustomer(customerRole);
    }
```
Therefore it seems you don't have a role named `ROLE_USER`. You'll need to run the following script to add that role.

```
 INSERT INTO BLC_ROLE (ROLE_ID, ROLE_NAME) VALUES (1,'ROLE_USER');
```

**Comment by vkhatri87** [comment]
Hi @cja769  @phillipuniverse  sorry for my seasonal comments(after long time), i am on the verge of closing this issue
The root cause is that Demo Site application is not able to connect with mysql database on VPS.
Despite providing the proper creds with db details  in properties file application is not able to connect.
in my case mysql db resides on same vps on which i am trying to run demosite, here i am able to connect from my local machine to vps mysql remotely but application is not able to do so.
Requesting you to please suggest, do i need to do anything apart from mentioning creds and db details in common.properties 
Becuase locally i have not faced this kind of connectivity issue(attaching server logs
[db_connection_errorlogs.txt](https://github.com/BroadleafCommerce/DemoSite/files/4920315/db_connection_errorlogs.txt)
)

Thanks in advance..
Vishnu Khatri.

**Comment by phillipuniverse** [comment]
The error logs that you sent do not indicate that there is a connection issue, just that there is no data in the result of the query. In the error log you sent, it has this:

```console
Caused by: javax.persistence.NoResultException: No entity found for query
        at org.hibernate.ejb.QueryImpl.getSingleResult(QueryImpl.java:286) ~[hibernate-entitymanager-4.1.11.Final.jar:4.1.11.Final]
        at org.broadleafcommerce.profile.core.dao.RoleDaoImpl.readRoleByName(RoleDaoImpl.java:51) ~[broadleaf-profile-5.2.2-GA.jar:na]
        at org.broadleafcommerce.profile.core.dao.RoleDaoImpl$$FastClassBySpringCGLIB$$f1174773.invoke(<generated>) ~[broadleaf-profile-5.2.2-GA.jar:na]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.10.RELEASE.jar:4.3.10.RELEASE]
```

Note the `NoResultException`, which means that it could not get data for the query.

This is the line that throws the exception: https://github.com/BroadleafCommerce/BroadleafCommerce/blob/5f2df96aef18ea017c586a845818456effb06d6d/core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/dao/RoleDaoImpl.java#L51

Based on the result of running this query: https://github.com/BroadleafCommerce/BroadleafCommerce/blob/5f2df96aef18ea017c586a845818456effb06d6d/core/broadleaf-profile/src/main/resources/config/bc/jpa/domain/Role.orm.xml#L29-L32

The solution that @cja769 presented is still the correct one based on your most recent log.

Also, if it could not actually connect to the database, you would get exceptions much, much earlier and the application would not start up at all.

**Comment by phillipuniverse** [comment]
@vkhatri87 have you taken a dump of the database that you have locally where it is fine, and then applied that data dump to the VPS mysql instance?

I suspect that the reason that you do not have data on the VPS MySQL instance is because the `blPU.hibernate.hbm2ddl.auto` is set to `update`, thus you never really had data in there to begin with. What `spring.profiles.active` environment are you running with when you start the application on your VPS?

**Comment by vkhatri87** [comment]
@phillipuniverse  thanks alot for your inputs.
yes i have taken a dump of db which i am running locally and have exported the same to VPS  mysql which is having valid data.
since i am not setting a specific environment so it falls under default profile.

**Comment by phillipuniverse** [comment]
Maybe then the application is connecting to a _different_ mysql instance than you think it is?

Again, everything you've sent so far is not a "cannot connect" issue but rather a missing data issue. Are you sure that the connection properties are pointing to the right MySQL instance _and schema_ on the VPS?

**Comment by vkhatri87** [comment]
@phillipuniverse 
yes the properties mentioned in mysql are something like 
database.url=jdbc:mysql://199.43.206.242:3306/broadleaf_rfs?useUnicode=true&amp;characterEncoding=utf8
and have connected with schema and verified data randomly like checking that in blc_role table there should be entry for name ='RULE_USER' etc.
but application logs prints as

2020-07-14 14:25:01.305 ERROR 29767 --- [nio-8443-exec-6] .BroadleafSimpleMappingExceptionResolver : Error caught and handled.:a1e9de61-1793-477e-8a2b-8d1df0c5a62c

org.springframework.dao.EmptyResultDataAccessException: No entity found for query; nested exception is javax.persistence.NoResultException: No entity found for query
        at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:392) ~[spring-orm-4.3.10.RELEASE.jar:4.3.10.RELEASE]

**Comment by cja769** [comment]
@vkhatri87 Can you you post the results of `SELECT * FROM BLC_ROLE` from that database you're targeting

**Comment by vkhatri87** [comment]
@cja769  there is only one entry with

**Comment by vkhatri87** [comment]
@cja769  there is only one entry with role_id = 1 and role_name = 'ROLE_USER' (attaching screenshot
![blc_roledata](https://user-images.githubusercontent.com/25980263/87463241-bb379a00-c62e-11ea-8573-65c261866f9e.png)
)

**Comment by cja769** [comment]
@vkhatri87 I can't tell which database you're connecting to but the user is broadleaf_rfs_new. I'm not sure how you have your database setup but I would confirm that the user that you're using in the command prompt matches the user that your application is using since the only thing I can think of is either your application is targeting an unpopulated database on the same host or it's using a different user that doesn't have the correct roles/permissions. You can also set `blPU.hibernate.show_sql=true` to show the SQL in the logs (I would suggest logging that to a separate file since it's pretty loud) and/or turning on statement logging on the MySQL side to make sure it's actually hitting that database. If this was a connection issue then it would say so. The driver should know the difference between getting no results and getting no response which is very different. Since it's saying no results then it's connecting and executing a query however it's not returning anything.

**Comment by vkhatri87** [comment]
Hi @phillipuniverse, @cja769 
I am closing the long pending above mentioned issue in which Broadleaf site was running smoothly on windows environment but was giving a trouble in Linux, since it was not able to fetch db records.
the issue was the table names in Ubuntu are case sensetive which i have fixed by changing mysqld.cnf (/etc/mysql/mysql.conf.d/mysqld.cnf) with below mentioned line and it is working as expected in Ubuntu VPS

lower_case_table_names=1

Thanks a ton for all your help and valuable inputs..
