### ISSUE TITLE
demo not working properly 

### ISSUE THREAD

**Issue by zumkpisces** [BroadleafCommerce/CommunityStarter#82]
I have visited the Demo site on the [https://demo.broadleafcommerce.org/mens](url). Most of the screens showing this error. Please help me to successfully execute it.

**Sorry, there was an error processing your request : 6c500960-b04e-481a-96a8-03d5da34a6d7**

I am interested in the development of the BroadLeafCommerce that's why I have started from the DemoSite. But unfornately the code deployed on the github is not working locally. 

If anyone can help me to get out of this, then I will be very thankful to him.

My email is:
zia_ul_mustafa@hotmail.com

**Comment by zumkpisces** [comment]
![broadleaf-error](https://user-images.githubusercontent.com/9819868/130443194-17ab3284-6a99-462f-b612-37b9825df659.PNG)

**Comment by riteshadhikari17** [comment]
This usually means solr needs to be re-indexed. Try reindexing from admin application.
