### ISSUE TITLE
Cannot add any item with sku to the cart 

### ISSUE THREAD

**Issue by mehmetsunkur** [BroadleafCommerce/CommunityStarter#9]
The finding matching sku process calls  filterCandidateSkusForArchivedStatus method below. This method returns null in all cases. So you cannot add any item with sku to the cart.

org.broadleafcommerce.core.catalog.dao.ProductOptionDaoImpl
protected List<Long>  filterCandidateSkusForArchivedStatus(List<Sku> candidateSkus)

But this method returns null in all cases. Because SkuImpl doesn't implement Status interface. So the condition never be true.
Sku sku = (Sku)var3.next();
            if(sku instanceof Status && !Objects.equals(((Status)sku).getArchived(), Character.valueOf('Y'))) {
                validCandidateSkuIds.add(sku.getId());
            }

**Comment by phillipuniverse** [comment]
Thanks for the report! This was definitely a regression that is now resolved in the latest 5.2.0-SNAPSHOT and will be apart of the 5.2.0-GA release.
